name: japan_fields
description: A simple way to use japanese data formats and patterns on your application
version: 0.1.0
homepage: https://github.com/geshner/japan_fields

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0